theme: jekyll-theme-cayman
title: Spotify Song Recommender
description: Welcome to my simple Spotify song recommender. Simply enter the title of one of your favorite songâ€™s and my algorithm will generate a song recommendation for you, which you can go and check out on https://www.spotify.com/us/ .
